# Generated by Django 4.1.7 on 2023-04-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['published_at'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
    ]
